baseURL: "https://kevin-souchard.github.io/"
title: Kevin Souchard
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20
taxonomies:
    tag: tags
menu:
    main:
        - name: Research
          url: papers/
          weight: 2
        - name: Teaching
          url: courses/
          weight: 3
params:
    description: "This website hosts Kevin Souchard's research, teaching materials, and contact information."
    author: Kevin Souchard
    # googleAnalyticsID: G-XXXXX
    DateFormat: January 2006
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: [courses, papers]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Kevin Souchard
          subtitle: "I am a PhD student at the [Bordeaux School of Economics](https://www.bse.u-bordeaux.fr/) under the supervision of Maïder Saint Jean and Ernest Miguelez. My research lies at the intersection of the economics of innovation, economic geography, and environmental economics, with a particular focus on technological complexity, technology diffusion, regional capabilities, and environmental policy."
          imageUrl: picture.jpeg
          imageWidth: 240
          imageHeight: 240
          buttons:
            - name: Research
              url: papers/
            - name: Teaching
              url: courses/
    socialIcons:
        - name: Email
          url: mailto:kevin.souchard@u-bordeaux.fr
        - name: LinkedIn
          url: https://fr.linkedin.com/in/kevin-souchard-b10080107
        - name: GitHub
          url: https://github.com/kevin-souchard
        - name: Location
          url: location/
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: Kevin Souchard
      icon: favicon.ico
      iconHeight: 18
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
